export const skills = [
  "Semantic & accessible HTML",
  "Responsive Web Design",
  "Markdown",
  "CSS BEM convention",
  "CSS Grid",
  "CSS Flexbox",
  "Styled-components",
  "TailwindCSS",
  "JavaScript ES6+",
  "TypeScript",
  "Immutability",
  "Vite",
  "React.js",
  "React Router",
  "Redux-Saga",
  "Redux (Toolkit)",
  "React Hooks",
  "Zustand",
  "Next.js 13",
  "Error handling",
  "Working with API (fetch, axios)",
  "TanStack Query",
  "Promises, Async/Await",
  "NPM",
  "PNPM",
  "Git",
  "GitHub Pull Requests & Review",
  "Trello",
  "Teamwork",
  "Scrum",
  "Figma"
];
